create table match(
    id varchar(30) primary key,
    country_id varchar(30),
    league_id varchar(30),
    season varchar(30),
    stage integer,
    date_game date,
    match_api_id varchar(30),
    home_team_api_id varchar(30),
    away_team_api_id varchar(30),
    home_team_goal integer,
    away_team_goal integer,

    home_player_1 varchar(30),
    home_player_2 varchar(30),
    home_player_3 varchar(30),
    home_player_4 varchar(30),
    home_player_5 varchar(30),
    home_player_6 varchar(30),
    home_player_7 varchar(30),
    home_player_8 varchar(30),
    home_player_9 varchar(30),
    home_player_10 varchar(30),
    home_player_11 varchar(30),
    away_player_1 varchar(30),
    away_player_2 varchar(30),
    away_player_3 varchar(30),
    away_player_4 varchar(30),
    away_player_5 varchar(30),
    away_player_6 varchar(30),
    away_player_7 varchar(30),
    away_player_8 varchar(30),
    away_player_9 varchar(30),
    away_player_10 varchar(30),
    away_player_11 varchar(30),

    foul_commit varchar(999999),

    B365H float,
    B365D float,
    B365A float,
    BWH float,
    BWD float,
    BWA float,
    IWH float,
    IWD float,
    IWA float,
    LBH float,
    LBD float,
    LBA float,
    PSH float,
    PSD float,
    PSA float,
    WHH float,
    WHD float,
    WHA float,
    SJH float,
    SJD float,
    SJA float,
    VCH float,
    VCD float,
    VCA float,
    GBH float,
    GBD float,
    GBA float,
    BSH float,
    BSD float,
    BSA float,

    foreign key (country_id) references country(id),
    foreign key (league_id) references league(id),
    foreign key (home_team_api_id) references team(team_api_id),
    foreign key (away_team_api_id) references team(team_api_id),

    FOREIGN KEY (home_player_1) REFERENCES player(player_api_id),
    FOREIGN KEY (home_player_2) REFERENCES player(player_api_id),
    FOREIGN KEY (home_player_3) REFERENCES player(player_api_id),
    FOREIGN KEY (home_player_4) REFERENCES player(player_api_id),
    FOREIGN KEY (home_player_5) REFERENCES player(player_api_id),
    FOREIGN KEY (home_player_6) REFERENCES player(player_api_id),
    FOREIGN KEY (home_player_7) REFERENCES player(player_api_id),
    FOREIGN KEY (home_player_8) REFERENCES player(player_api_id),
    FOREIGN KEY (home_player_9) REFERENCES player(player_api_id),
    FOREIGN KEY (home_player_10) REFERENCES player(player_api_id),
    FOREIGN KEY (home_player_11) REFERENCES player(player_api_id),
    FOREIGN KEY (away_player_1) REFERENCES player(player_api_id),
    FOREIGN KEY (away_player_2) REFERENCES player(player_api_id),
    FOREIGN KEY (away_player_3) REFERENCES player(player_api_id),
    FOREIGN KEY (away_player_4) REFERENCES player(player_api_id),
    FOREIGN KEY (away_player_5) REFERENCES player(player_api_id),
    FOREIGN KEY (away_player_6) REFERENCES player(player_api_id),
    FOREIGN KEY (away_player_7) REFERENCES player(player_api_id),
    FOREIGN KEY (away_player_8) REFERENCES player(player_api_id),
    FOREIGN KEY (away_player_9) REFERENCES player(player_api_id),
    FOREIGN KEY (away_player_10) REFERENCES player(player_api_id),
    FOREIGN KEY (away_player_11) REFERENCES player(player_api_id)
);